name: docker

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  all-in-one-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build all-in-one image
        run: docker build -t esxi-iso-builder:ci .
